#
# CircleCI configuration for angular-starter
#

version: 2
jobs:
  build:
    working_directory: ~/angular-starter
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-starter-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm i --no-progress
      - save_cache:
          key: angular-starter-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
      - run: xvfb-run -a npm run test -- --single-run --code-coverage --no-progress --browser=ChromeNoSandbox
      - run: xvfb-run -a npm run e2e -- --no-progress
      - run: npm run coverage
